// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoB6ClywerbKiI660zojHyJK_WQp-wY0',
    appId: '1:59248450177:web:f292870ede161a53d2cb80',
    messagingSenderId: '59248450177',
    projectId: 'todo-e0f09',
    authDomain: 'todo-e0f09.firebaseapp.com',
    storageBucket: 'todo-e0f09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN6ahGcit7gP5uBJRM0Q-DRD4JhWT8cxo',
    appId: '1:59248450177:android:f989a859ce3b077bd2cb80',
    messagingSenderId: '59248450177',
    projectId: 'todo-e0f09',
    storageBucket: 'todo-e0f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGavAPqrBsf2qHeEglfuSCTee9M6X2dxg',
    appId: '1:59248450177:ios:a58b2a777da05ce0d2cb80',
    messagingSenderId: '59248450177',
    projectId: 'todo-e0f09',
    storageBucket: 'todo-e0f09.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGavAPqrBsf2qHeEglfuSCTee9M6X2dxg',
    appId: '1:59248450177:ios:a58b2a777da05ce0d2cb80',
    messagingSenderId: '59248450177',
    projectId: 'todo-e0f09',
    storageBucket: 'todo-e0f09.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWoB6ClywerbKiI660zojHyJK_WQp-wY0',
    appId: '1:59248450177:web:369ea34d214817f6d2cb80',
    messagingSenderId: '59248450177',
    projectId: 'todo-e0f09',
    authDomain: 'todo-e0f09.firebaseapp.com',
    storageBucket: 'todo-e0f09.firebasestorage.app',
  );
}
